In [1]:
from scipy.stats import zscore
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("landslide_dataset.csv")
data

,Rainfall_mm,Slope_Angle,Soil_Saturation,Vegetation_Cover,Earthquake_Activity,Proximity_to_Water,Landslide,Soil_Type_Gravel,Soil_Type_Sand,Soil_Type_Silt
0,206.181018,58.275001,0.892798,0.339463,4.390047,0.099975,1,0,0,0
1,218.887334,36.679801,0.657147,0.360355,4.141029,0.832443,1,0,0,1
2,181.850867,31.363874,0.673362,0.221697,5.311891,0.023062,1,0,0,1
3,228.716199,38.995134,0.618666,0.489502,4.581928,0.785176,1,0,0,1
4,179.951067,42.998205,0.836966,0.118580,5.518862,0.450499,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...
1995,195.650778,27.084662,0.567332,0.556801,3.472594,1.323190,0,1,0,0
1996,197.339684,22.715510,0.037470,0.517580,0.673632,1.921158,0,1,0,0
1997,75.759674,6.631750,0.266207,0.925309,0.306690,1.944876,0,0,1,0
1998,50.919297,16.603380,0.014794,0.954346,2.073630,1.111595,0,1,0,0
1999,188.083126,28.372795,0.093188,0.516938,3.959366,1.043214,0,1,0,0

In [4]:
s=data["Rainfall_mm"]
s

0       206.181018
1       218.887334
2       181.850867
3       228.716199
4       179.951067
           ...
1995    195.650778
1996    197.339684
1997     75.759674
1998     50.919297
1999    188.083126
Name: Rainfall_mm, Length: 2000, dtype: float64

In [6]:
result=zscore(s)
#print("a",a)
print("z-scores",result)
#result

z-scores [ 0.44884098  0.64221572  0.07856555 ... -1.53601388 -1.91405433
  0.17341299]